const { default: Link } = require("next/link");
import React, { children } from 'react'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

function layout({ children }){
    return (
        <>
            <div className='divTienda'>
                <Link href="/tienda/electronica">Electronica</Link>
                <br></br>
                <br></br>
                <Link href="/tienda/decoracion">Decoración</Link>
                <br></br>
                <br></br>
                <Link href="/tienda/mobiliario">Mobiliario</Link>
                <br></br>
                <br></br>
                <Link href="/tienda/libros">Libros</Link>
            </div>
            
            <body>{children}</body>
        </>
    )
}

export default layout
