import './globals.css'
import Navbar from './navbar'

export const metadata = {
  title: 'Ejemplo de app en NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { 
  return ( 
    <html lang="es">
      <body className=""> 
        <Navbar></Navbar>
        {children} 
      </body>
    </html>
  )
}
