import Link from "next/link"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
    return (
        <html lang="en">
            <Link href="/blog/blog1">Blog 1</Link>
            <br></br>
            <Link href="/blog/blog2">Blog 2</Link>
            <br></br>
            <Link href="/blog/blog3">Blog 3</Link>
            <body>{children}</body>
        </html>
    )
}